// import './instance'
// import './lifecycle'
// import './data-binding'
// import './computed'
// import './directive'
// import './component/define'
// import './component/extends'
// import './component/v-model'
// import './component/feature'
import './component/render'

